# Generated by Django 4.2.20 on 2025-07-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_artisan', models.TextField(blank=True)),
                ('boutique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('suspendu', 'Suspendu'), ('supprime', 'Supprimé')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('note_moyenne', models.FloatField(default=0)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('formations_suivies', models.JSONField(blank=True, default=list)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='artisans/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
