# Generated by Django 4.2.20 on 2025-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artisanprofile_attestation_enregistrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='artisans/qr_codes/'),
        ),
    ]
