# Generated by Django 4.2.20 on 2025-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artisanprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='galerie',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='profil_complet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
