# Generated by Django 4.2.20 on 2025-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
